{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
<head>
    <title>Netgen Connect</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-language" content="en-US" />
    <meta name="author" content="Netgen d.o.o." />
    <meta name="copyright" content="Netgen d.o.o." />
    <meta name="description" content="Netgen Connect eZ Publish extension by Netgen d.o.o." />
    <meta name="keywords" content="social networks, facebook, twitter, tumblr, google, ezpublish, netgen, ngconnect, netgen connect" />
</head>
<body>
    <script type="text/javascript">
        {if and( ezhttp_hasvariable( 'NGConnectRedirectToProfile', 'session' ), ezhttp( 'NGConnectRedirectToProfile', 'session' )|eq( 'true' ) )}
        window.opener.location = '{'ngconnect/profile'|ezurl( no, full )}';
        {else}
        window.opener.location.reload();
        {/if}
        window.close();
    </script>
</body>
</html>
